### ISSUE TITLE
Unable to get proper error message when the post methods fails

### ISSUE THREAD

**Issue by ARJUN-R34** [getsafle/safle-identity-wallet#2]
When the set handlename or update handlename method is called and if the conditions are not met in the smart contract, then there is no proper error message getting returned.

Instead, the error message for every scenario is just the same, which is the default one, 
```Transaction has been reverted by the VM```

Need to implement proper error messages in the smart contract level.

**Comment by apoorvq** [comment]
This is because there are two contract call happening, one by EOA and one by CA. The Contract returns error message to the first contract and that is not able to return the same error.

This can be rectified by using **tunnel messaging** between contracts in case of errors.

**Comment by ARJUN-R34** [comment]
Added `try/catch` to handle uncaught errors.
